stages:
  - build
  - test
  - dockerize
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end"
  DOCKER_IMAGE: registry.example.com/myapp:$CI_COMMIT_SHA

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - echo "Building the project..."
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar
  only:
    - master

test:
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn $MAVEN_CLI_OPTS test
  only:
    - master

dockerize:
  stage: dockerize
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE .
    - echo "Pushing Docker image to registry..."
    - docker push $DOCKER_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "Deploying to Kubernetes..."
    - kubectl set image deployment/myapp myapp=$DOCKER_IMAGE --record
  only:
    - master
  environment:
    name: staging
    url: http://staging.example.com
